import CandleStickChartWithCHMousePointer from "./CandleStickChartWithCHMousePointer"
import updatingDataWrapper from "./updatingDataWrapper"


const CandleStickChartWithUpdatingData = updatingDataWrapper(CandleStickChartWithCHMousePointer)


export default CandleStickChartWithUpdatingData